zlib: fix compile error when 'DEBUG' is defined
When a file that includes zutil.h is being compiled with the CPP
symbol 'DEBUG' defined, compilation fails with the error message:
|lib/zlib/zutil.h:105:40: error: implicit declaration of function 'fprintf' [-Werror=implicit-function-declaration]
|  105 | #  define Tracevv(x) {if (z_verbose>1) fprintf x ;}
|      |                                        ^~~~~~~

Fix this by uncommenting the include of stdio.h in zutil.h.
<stdio.h> is available in U-Boot since
commit 7fea7b1a37ad ("stdio.h: move printf() stuff from <common.h> to <stdio.h>").

Fix some indentation bugs along the way.